### PR TITLE
Small repo cleanup

### PR DESCRIPTION
**Pull request by lietu**
I looked through the repository and fixed a few issues, feel free to take these into use.

1. `pre-commit` is used for enforcing a common code style and formatting everywhere
2. `poetry` is used for managing Python dependencies, which also includes proper locking
3. `README` has been updated with this information
4. `Dockerfile` now works and uses non-ancient versions of software, it also runs the `deaths_scraper.py` since that seems to be necessary
5. Other basic tools and quick manual review have been used to fix the unused imports, copying of code, and not sticking to PEP-8 in Python scripts
6. The fragile part of the Python scripts which apparently regularly fails due to some inconsistency of data has been made to automatically retry a few times - this seems to pretty much fix the script
7. Simplistic workaround for `NaN` values ending up in JSON from Python - something that Python really should fix but refuses, for now this solution seems to work
8. Added `deaths.json` to repo so others don't have to try and figure out where to get the history data, would be nice if you kept this up-to-date as well - a `git push origin master` shouldn't be too much work to do every now and then
9. Fixed some quick typos that were easy to fix with a `Replace all in files...`

There should be no actual changes to functionality on how the Python scripts or frontend work or the results they produce - except in the potentially increased stability.

### CODE REVIEW

**Comment by neuroactive** [comment]
@lietu Many thanks for the pull request. This all looks very useful and I'm in the process of reviewing your changes.

With regard to item 7 in your list, is this change likely to have any impact on the the statistics which are displayed in the app? I was aware that sometimes the data update process would fail, with Python complaining about NaN values in the JSON data. I was under the impression that these were caused by invalid values in the source data from TEHIK. Is that your understanding of the situation? If that is the case, I am wondering if it would be preferable for that particular update attempt to fail completely rather than to include invalid data in the JSON which gets used by the app.

Using pre-commit seems like a good idea, although I have mixed feelings about some of the specific changes made by the code formatters. For example, in the Vue templates, it has always seemed to me to be a very inefficient use of space to format code so that a closing angled bracket goes on its own line. The recommended style has the effect of increasing the number of lines of code, which makes it harder to see the overall structure of templates (I appreciate that this is the style suggested by the Vue maintainers themselves). My preferred style would be something of a compromise where the first attribute goes on the same line as the opening tag, subsequent attributes are aligned beneath that, and the closing tag is placed on the same line as the last attribute. Also, a small point, but replacing `<br>` with `<br />` doesn't really seem like an improvement as `<br>` is valid HTML5, takes up less bytes, and is easier to read. In general, the Python code does looks much better, especially with respect to the naming conventions. It would increase the readability of the code in my opinion if we increase the maximum line length to 99 characters, which is something PEP 8 floats as a possibility.

Retrying the data downloads is a good idea, although I plan to reduce the number of retries to avoid hitting TEHIK's system with requests when the data just hasn't been published yet. I think we can also make some further improvements here so that data which has already been downloaded and found to be OK is not redownloaded if data from one of the other endpoints is found to be problematic. I can implement your changes, but will open a new issue about further improvements to the data update process.

**Comment by lietu** [comment]
Quick comments for now:

1) I have no idea if the point 7 has any impact on what is showed on the app - though I did not notice any obvious issues .. still I have no idea where the `NaN` values even are used

someone who knows the app better and has the ability to test it should figure out how to detect such errors and raise errors then, the issue is caused somewhere deep in the logic that I didn't have time or interest to look into at this stage

writing to files is now correct as it was previously writing invalid data basically due to how numpy and json package interact - however bad data in bad data out applies

2) The main point with code formatters is that people stop having pointless discussions about style, e.g. this: `Also, a small point, but replacing <br> with <br /> doesn't really seem like an improvement as <br> is valid HTML5, takes up less bytes, and is easier to read.` - seriously saving 2 bytes is not a problem here, it is not even that with gzip properly configured. The main problem tools like that solve is having discussions exactly like that one - `<br>` vs `<br />` is not a productive discussion where anyone can afterwards say it was time well spent. However you can also configure them - personally I prefer less configurability over more configurability so people can't waste time on discussing the formatter configuration either.

https://www.youtube.com/watch?v=esZLCuWs_2Y is a great talk on the subject and specifically on the Python code formatter

3) `to avoid hitting TEHIK's system with requests when the data just hasn't been published yet` - that's not what retries are for, retries are for recoverable errors, if it seems they have not published the data yet you should raise an irrecoverable exception instead .. also there's a 5 second timeout between the requests, if TEHIK's systems can't handle that there is something seriously wrong with them .. generally it seemed the data requesting could be optimized a whole lot

for now this was similar as to 1) - making the thing work in general, some additional work needs to be put into figuring out the causes of the issues and how to handle them properly

**Comment by neuroactive** [comment]
@lietu Thanks for your comments and sorry for the delay in replying.

I've now merged your changes, with some modifications.

I wasn't able to get "pre-commit" working on my Windows 10 machine, despite following the instructions closely. I understand it has some potential benefits, but I have removed the requirement for that from the project as I would like the set-up process to be as simple as possible and my personal experience didn't leave me feeling confident that that would be the case if it remained as a prerequisite. I understand there are alternative ways we can implement some checks on push requests at Github, without requiring the user to install anything.

I haven't used poetry before, but it does seem to have some benefits, so I'm happy to give it a try. I got it installed locally and on the server without any problems, and it appears to be working. I had to reduce the minimum Python version to 3.8 to match the one available on the server. There were a couple of errors in the README instructions related to poetry, but they are now fixed.

> Quick comments for now:
> 
> 1. I have no idea if the point 7 has any impact on what is showed on the app - though I did not notice any obvious issues .. still I have no idea where the `NaN` values even are used

It seems there are some places in the test location data where "null" values appear in the JSON, for example when listing the population density of test results where the location of the test subject is "Unknown". So we do need to be able to deal with these gracefully.

> someone who knows the app better and has the ability to test it should figure out how to detect such errors and raise errors then, the issue is caused somewhere deep in the logic that I didn't have time or interest to look into at this stage
> 
> writing to files is now correct as it was previously writing invalid data basically due to how numpy and json package interact - however bad data in bad data out applies

Great.

> 1. The main point with code formatters is that people stop having pointless discussions about style, e.g. this: `Also, a small point, but replacing <br> with <br /> doesn't really seem like an improvement as <br> is valid HTML5, takes up less bytes, and is easier to read.` - seriously saving 2 bytes is not a problem here, it is not even that with gzip properly configured. The main problem tools like that solve is having discussions exactly like that one - `<br>` vs `<br />` is not a productive discussion where anyone can afterwards say it was time well spent. However you can also configure them - personally I prefer less configurability over more configurability so people can't waste time on discussing the formatter configuration either.
> 
> https://www.youtube.com/watch?v=esZLCuWs_2Y is a great talk on the subject and specifically on the Python code formatter

I did watch the video about it, which was interesting. However, I reviewed various parts of the code where auto-formatting made changes and overall I don't feel we should use it in this project. My main concerns are over the overall readability of the code. Yes, the auto-formatters make the code consistent, but the downside is that they can significantly inflate the number of lines and can make the overall structure of the code harder to read. However, most of the changes made by the autoformatting you carried out have been retained, with some exceptions where I thought the original was more readable.

> 1. `to avoid hitting TEHIK's system with requests when the data just hasn't been published yet` - that's not what retries are for, retries are for recoverable errors, if it seems they have not published the data yet you should raise an irrecoverable exception instead .. also there's a 5 second timeout between the requests, if TEHIK's systems can't handle that there is something seriously wrong with them .. generally it seemed the data requesting could be optimized a whole lot

Yes, but the problem is that the script doesn't know whether it is dealing with the scenario where the data hasn't been published yet or it a recoverable error (as was the case last week when a caching problem at TEHIK meant that on some requests out-of-date data was returned even though fresh data was available). In total, the data from TEHIK takes about 30 seconds to download. Retrying every endpoint if a single one of them fails, and doing so 15 times, isn't going to crash TEHIK's system, but it isn't a good use of resources either to keep downloading data for eight minutes straight when the most likely scenario is that the data simply hasn't been published yet for a particular day.

Anyway, I have given the code which updates the data in main.py a rewrite with the aim of making it more efficient and so that it handles errors better. It is now set up to retry any endpoint which fails up to three times, but not to retry any endpoint where data has been successfully retrieved. In the future, I plan to move to a structure where a single broken endpoint doesn't automatically cause the entire update process to fail.

> for now this was similar as to 1) - making the thing work in general, some additional work needs to be put into figuring out the causes of the issues and how to handle them properly

One final thing to mention, I have had to remove deaths.json from the Git repo for now as the data folder on the server contains the "master" copy of the deaths data. Leaving deaths.json in the repo would leave it liable to be accidentally overwritten by changes, which is problematic as TEHIK doesn't publish full data on deaths. In any case, I am planning to change the structure of the app so that the need to download data locally is removed. Instead, the data will be downloaded from an API endpoint on the project's server. So the fact that users cloning the project won't have access to the deaths data is something of a temporary problem.

Thanks for the time you put into this. Overall, I think there are some good improvements in this update, which should make it easier to develop the app going forward.

**Comment by lietu** [comment]
> I wasn't able to get "pre-commit" working on my Windows 10 machine, despite following the instructions closely. I understand it has some potential benefits, but I have removed the requirement for that from the project as I would like the set-up process to be as simple as possible and my personal experience didn't leave me feeling confident that that would be the case if it remained as a prerequisite. I understand there are alternative ways we can implement some checks on push requests at Github, without requiring the user to install anything.

That's strange, I am running on Windows 10, but I've been scripting basic environment setup for myself for a long time so I'm not exactly sure if there could be other issues with it. Could you maybe share what kind of issues you ran into, and maybe I can help out with that and improving instructions?

The main difference between `pre-commit` and doing it on Travis-CI or GitHub workflows is "shift-left" - as in, the less time you have to wait to get the feedback the better the results are and the easier it is to react to it.

>  Retrying every endpoint if a single one of them fails, and doing so 15 times, isn't going to crash TEHIK's system, but it isn't a good use of resources either to keep downloading data for eight minutes straight when the most likely scenario is that the data simply hasn't been published yet for a particular day.

Totally, which is why the download should be separated from the `main.py` logic similar to `deaths_scraper.py` - something like `update_data.py` which downloads each item, only once, and raises an exception if something seems off so `set -e` on a BASH script will abort there when it seems the automatic data update fails and won't needlessly continue.

>  Leaving deaths.json in the repo would leave it liable to be accidentally overwritten by changes, which is problematic as TEHIK doesn't publish full data on deaths.

You could also ensure that you commit the update every time you automatically update it, something akin to

```bash
set -e
python deaths_scraper.py
cd ..
git add data/deaths.json
git commit -m "Updated deaths data"
```

I've done some such scripts in the past pretty successfully. Alternatively you could leave `deaths.json` in as a `deaths.sample.json` or similar.

**Comment by neuroactive** [comment]
@lietu Thanks for your reply. Please see my comments below.

> > I wasn't able to get "pre-commit" working on my Windows 10 machine, despite following the instructions closely. I understand it has some potential benefits, but I have removed the requirement for that from the project as I would like the set-up process to be as simple as possible and my personal experience didn't leave me feeling confident that that would be the case if it remained as a prerequisite. I understand there are alternative ways we can implement some checks on push requests at Github, without requiring the user to install anything.
> 
> That's strange, I am running on Windows 10, but I've been scripting basic environment setup for myself for a long time so I'm not exactly sure if there could be other issues with it. Could you maybe share what kind of issues you ran into, and maybe I can help out with that and improving instructions?

As per the instructions, I installed it using `pip3 install pre-commit`. If I run `pip3 freeze`, then `pre-commit=2.12.1` shows up in the list of installed libraries. But if I go to the root of the repo (using Windows Powershell as an admin user) and run `pre-commit install`, as in the proposed README instructions, then I get the following error message:

```
pre-commit : The term 'pre-commit' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

If I try the same command using the bash shell included with Windows git, then I get:

```
bash: pre-commit: command not found
```

> The main difference between `pre-commit` and doing it on Travis-CI or GitHub workflows is "shift-left" - as in, the less time you have to wait to get the feedback the better the results are and the easier it is to react to it.

True, but it does come at the cost of a more complex set-up process for the individual developer. That may not be a significant issue for a professional team, but it's potentially a bigger issue for a project where a lot of the contributors may be relatively inexperienced and where time is limited to help people who do run into problems. I think there's a reasonable argument that for this project we should try to keep the prerequisites as simple as possible.

> > Retrying every endpoint if a single one of them fails, and doing so 15 times, isn't going to crash TEHIK's system, but it isn't a good use of resources either to keep downloading data for eight minutes straight when the most likely scenario is that the data simply hasn't been published yet for a particular day.
> 
> Totally, which is why the download should be separated from the `main.py` logic similar to `deaths_scraper.py` - something like `update_data.py` which downloads each item, only once, and raises an exception if something seems off so `set -e` on a BASH script will abort there when it seems the automatic data update fails and won't needlessly continue.

I have given the code to update the data a fairly comprehensive review, and it should handle retries and errors better now. I have renamed main.py to update_data.py, and merged the deaths scraper into that module. There was a lot of redundant code which I have cut out. I am going to move the code to restart Node there if no problems have been encountered. As soon as I can get the app data to load asynchronously (#243), then there will no longer be a need to restart Node when the update process happens.

> > Leaving deaths.json in the repo would leave it liable to be accidentally overwritten by changes, which is problematic as TEHIK doesn't publish full data on deaths.
> 
> You could also ensure that you commit the update every time you automatically update it, something akin to
> 
> ```shell
> set -e
> python deaths_scraper.py
> cd ..
> git add data/deaths.json
> git commit -m "Updated deaths data"
> ```
> 
> I've done some such scripts in the past pretty successfully. Alternatively you could leave `deaths.json` in as a `deaths.sample.json` or similar.

Saving the updates to git is theoretically possible, but leaving deaths.json in the repo does still leave the possibility of accidental editing by a contributor, plus automatically pushing to git can cause problems with merge conflicts under certain circumstances. Leaving it in as deaths.sample.json is also a possibility, but that would also need updating. I think the simplest solution is if we make the deaths.json available at an endpoint hosted at koroonakaart.ee so that the latest version can be downloaded. In general, this is something of a temporary problem as the plan is to develop an API (#242 ) and then make the app load its data from that. So the need for individual data files to be packaged with the app will be removed.

**Comment by lietu** [comment]
> then I get the following error message

If CLI utilities installed via `pip` are not added to your path, then your Python installation is incomplete. It should be properly set up by the Python installer if you choose the settings right, but I've seen a few situations where it is not. In my case I need e.g. `c:\Users\<username>\AppData\Roaming\Python\Python39\Scripts` to be in my `PATH`, this may in your case a bit different, and I've seen e.g. `c:\python39` being the installation root and so `c:\python39\scripts` also needs to be added.

> True, but it does come at the cost of a more complex set-up process for the individual developer.

Should simply require you to have installed Python normally. In case people run into issues it should be fine to add the suggestion that one needs to add their `<python install path>\Scripts` to their `PATH` with a link to some generic guide on how to edit PATH, e.g.: https://datatofish.com/add-python-to-windows-path/

> In general, this is something of a temporary problem as the plan is to develop an API

Sure seems like you're planning on ensuring the system will be more slow and unstable rather than more stable in the future, especially considering none of the features seem to need or benefit from that, but you do you.

**Comment by neuroactive** [comment]
> > then I get the following error message
> 
> If CLI utilities installed via `pip` are not added to your path, then your Python installation is incomplete. It should be properly set up by the Python installer if you choose the settings right, but I've seen a few situations where it is not. In my case I need e.g. `c:\Users\<username>\AppData\Roaming\Python\Python39\Scripts` to be in my `PATH`, this may in your case a bit different, and I've seen e.g. `c:\python39` being the installation root and so `c:\python39\scripts` also needs to be added.

My Python version is the one available at the Windows Store and I believe I used the default installation settings.

> > True, but it does come at the cost of a more complex set-up process for the individual developer.
> 
> Should simply require you to have installed Python normally. In case people run into issues it should be fine to add the suggestion that one needs to add their `<python install path>\Scripts` to their `PATH` with a link to some generic guide on how to edit PATH, e.g.: https://datatofish.com/add-python-to-windows-path/
> 
> > In general, this is something of a temporary problem as the plan is to develop an API
> 
> Sure seems like you're planning on ensuring the system will be more slow and unstable rather than more stable in the future, especially considering none of the features seem to need or benefit from that, but you do you.

I'm not sure how you've concluded that the proposals will lead to a slower and more unstable app. The current structure of requiring one large monolithic data file in order to compile the app isn't efficient or stable at all. There needs to be better separation of the front-end code from the data, and the data needs to be made available in smaller pieces. This will allow the rendering of the page to start much earlier, the app won't be as sensitive to problems with any particular part of the data, and the need to package the data with the app will be removed.

**Comment by lietu** [comment]
> My Python version is the one available at the Windows Store and I believe I used the default installation settings.

That could well be the root of your issues, Windows Store does a lot of stupid things, and I wouldn't be surprised if this was one of them. The most reliable way to install Python on Windows is via the official installer https://www.python.org/downloads/

Either way, adding the `scripts` to your `PATH` should fix your Python installation, it's the directory where Python puts all the globally installed utilities by default. Once you have run `pip install pre-commit` you can figure out which directory to add to your `PATH` by running `where /r c:\ "pre-commit.exe"`  -which will locate the file and tell you where it is on your system, and then you can follow https://datatofish.com/add-python-to-windows-path/


> I'm not sure how you've concluded that the proposals will lead to a slower and more unstable app

Simple - current system is built so that it fetches data, does some calculation, then builds a *static* website that can be hosted on any "serverless" platform and cached super efficiently. Once the files are loaded, no additional requests are done.

You seem to be planning to build an API - these are connected to databases, databases usually take some maintenance, large changes in database structures often take downtime, and people regularly mess up releasing code that depend on changes that are not yet in the DB. Additionally APIs often run on servers, and looking at the history of how this has been hosted, you probably would be running it on some relatively manual hosting solution instead of e.g. Google Cloud Run, meaning more instability for releases.

You can do all the things you proposed about not depending on one large monolithing data file, loading the page sooner, and increased reliability - just by refactoring the scripts to work separately and produce more sane separated output files. 

Additionally you could still ensure that once a build is made, the website can be published literally anywhere, delivery can be massively optimized and scaled to infinite without any delay. When the hosting is changed to use e.g. GitHub pages, or any other cost-effective static site hosting system, and Cloudflare or similar global CDN cache is slapped in front, the performance is blazing fast and there is little chance of downtime - assuming the build scripts are sane. And the final bill for this hosting is 0€.

You *can* build scalable and fast solutions with APIs and backends, but the investment in those is massive and benefits for a system like this are non-existent, just the opposite - there are negative effects and zero positives.

**Pull request merged**
