### PR TITLE
Automatically set default langauge #63

### PR DESCRIPTION
**Pull request by muhammednagy**

### CODE REVIEW

**Comment by keeganmcbride** [comment]
Shouldn't we add a test / check in incase the language is not included in our locale files?

**Comment by keeganmcbride** [comment]
Or nvm it should default to et.

**Comment by keeganmcbride** [comment]
Will look into this a bit more, some users have their Chrome, for ex, set to English, but are Estonian speakers. So even if navigating to koroonakaart.ee/et it still overides and goes to English (feedback from my team). Not sure how to approach it, need to think a bit more.

**Comment by keeganmcbride** [comment]
@muhammednagy  Perhaps we should add a check to make sure that this only applies when koroonakaart.ee is the domain, koroonakaart.ee/et should still redirect to Estonian, /RU to russian, and /en to English I guess.

**Comment by muhammednagy** [comment]
okay will do update it to do that.
Thanks for the feedback!

**Comment by muhammednagy** [comment]
oh nvm @keeganmcbride 
seems like @Kypsis  already fixed it.
didn't think about that sorry.

**Pull request merged**
