### PR TITLE
Add active cases estimate from county population to map and graph

### LINKED ISSUE #212: Active percentage per county
I suggest adding a new map option that displays the active cases percentage for every county. Population numbers can be obtained here (every January) https://www.siseministeerium.ee/et/eesmark-tegevused/rahvastikutoimingud/rahvastikustatistika

### PR DESCRIPTION
**Pull request by sarnane**
Fix #212 
Screenshot from 2021-03-08 14-08-45
Screenshot from 2021-03-08 14-09-46

### CODE REVIEW

**Comment by dorkster100** [comment]
sorry to keep you waiting, a mild confusion occurred, i will inspect and merge this PR after the small issue is fixed on the server.

Thank you for your contributions.

**Comment by dorkster100** [comment]
@sarnane @neuroactive so this is a weird PR to merge, my issue here is that this new view of the data is exact copy of 14-day cumulative per 100 000, just divided by 1000.

I will show you example of local version:
image
image

So i have not checked the data, but one of those is wrong, either the new data is not percent of population or 14-day cumulative is not per 100 000.

**Comment by neuroactive** [comment]
"my issue here is that this new view of the data is exact copy of 14-day cumulative per 100 000, just divided by 1000"

I believe that is to be expected. The active cases estimate is just a sum of the total number of cases over the past two weeks.

As both of these views effectively show the same thing, i.e. the number of infections over the past two weeks relative to the population, we should perhaps consider whether we could display both statistics on the same map. The only difference is really the units involved.

I think we can go ahead and merge this anyway. Having the extra view will make it convenient for people who prefer to see the infection level as a percentage.

**Comment by neuroactive** [comment]
@sarnane @dorkster100 We should make some decision about what to do with this. There are four options as I see it:

(i) We merge the pull request as it is.
(ii) We create an "Infection rate" view and add a separate control which allows the user to select whether they wish to see the infection rate as a percentage or as the number of cases per 100,000 people.
(iii) We drop the "14-day cases per 100,000" view but keep this one.
(iv) We drop this view but keep the "14-day cases per 100,000" one.

There are good reasons why people might want to see the infection rate both as a percentage and as the number of cases per 100,000. Some people will find a percentage easier to understand, but the rate per 100,000 offers an easier comparison with the national and international figures which are quoted in the media. So I think we should make it possible for the user to see whichever they prefer. Option (ii) is technically more complicated and would add some inconsistency to the interface, so overall I'm in favour of option (i).

What are your thoughts?

**Comment by dorkster100** [comment]
I think we do not really need most of the changes implemented in this PR. We can use existing code and have numbers divided by 1000 in parentheses with% sign.

Also if I understand correctly numbers are equal here because person is not counted as active case after 14 days? In that case I am not sure that the proposed statistics is good, because current version is more clear.

**Pull request closed without merging**
