### PR TITLE
Add percentages to daily cases graph

### PR DESCRIPTION
**Pull request by metsjeesus**

### CODE REVIEW

**Comment by metsjeesus** [comment]
resolves  #1

**Comment by keeganmcbride** [comment]
Testing.

**Comment by keeganmcbride** [comment]
Reverted for now as we investigate how to display it better. The scale is a bit off and probably could use a second axis for the percentage.

**Comment by metsjeesus** [comment]
Im not familiar with that graphic library. Tried to make second y-axis, could not make it succesfully. Feel free to change, im out of ideas moment.

**Comment by keeganmcbride** [comment]
@metsjeesus One way to approach this would be a stacked or regular bar chart that showed the negative / positive as percentage per day.

**Pull request merged**
