### PR TITLE
Add Github actions (CI) support + Docker support

### PR DESCRIPTION
**Pull request by aldas**
This pull request adds some automation and deploy support

Added:
1.  Added Github actions support (https://github.com/features/actions). Now deploy artifacts can be built manually by triggering workflow action in Gitub GUI (manually because not to fetch too frequently open data). To run workflow: go to `Actions` and click `Run workflow` button at right side of screen. This will be visible when action is merged to main branch.
    Workflow definition is here: ```.github/workflows/package.yml```

2. Added [Docker](https://www.docker.com/) support to create own images with koroonakaart (nginx is serving frontend)  
    ```
    docker build -t koroonakaart .
    
    # run container in foreground (open http://localhost:8080)
    docker run --rm -p 8080:80 --name koroona koroonakaart:latest
    ```

### CODE REVIEW

**Comment by keeganmcbride** [comment]
Since deceased data is not available via TEHIK this needs to either be scraped from Terviesamet webpage, or entered manually in the morning. This approach atm won't fully work in this situation, but definitely will merge once there is a work around.

**Comment by aldas** [comment]
I think manually updating main.py could be considered different issue and does not affect this solution. Assuming there is updated main.py. These actions will use them -  both github actions workflow and docker will as first step generate up to date json with python and if it was updated before then rest is up to date. 

basically all this could be achieved even in browser -  update `main.py` with github editor, commit changes and then manually start workflow to produce frontend artifacts (json included)

**Comment by keeganmcbride** [comment]
Ah, yes, of course. Sorry been a crazy day... Will merge.

**Comment by keeganmcbride** [comment]
Thanks!

**Comment by aldas** [comment]
@keeganmcbride You should be able to run workflow manually as it is in main branch now. Check `Actions` tab and look for `Run workflow` button at right side of screen.

See: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Pull request merged**
