### PR TITLE
Fixed typos and spelling in the russian translation.

### PR DESCRIPTION
**Pull request by artemtam**

### CODE REVIEW

**Comment by asborisov** [comment]
Can you please include another translation for `recovered`? It's `Discharged from hospital` in [en](https://github.com/okestonia/koroonakaart/blob/master/koroonakaart/src/locales/en.json#L40) now

**Comment by keeganmcbride** [comment]
Feel free to suggest something, sorry that none of us speak Russian so was unable to translate this when I did the other two.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by artemtam** [comment]
I changed "Recovered" to "Discharged from hospital". Though it sounds not natural even in English, so probably makes sense to have "Recovered" there.

**Comment by asborisov** [comment]
The main problem, I can see with `recovered` is that it's not really recovered people but only those who got hospitalized and discharged from hospital later.

**Pull request merged**
