### PR TITLE
Fix language issue #37

### PR DESCRIPTION
**Pull request by ivaravi**
#37 pull request

### CODE REVIEW

**Comment by keeganmcbride** [comment]
Did you check this locally? We just added something in https://github.com/okestonia/koroonakaart/commit/597b93a9fe5720d09894ca3535759ed176c18f02and https://github.com/okestonia/koroonakaart/commit/3e5e5f9514b63eafd8940528e1aa9f1a608f5335

**Comment by keeganmcbride** [comment]
Well, it turns out sleep is important. Thanks for the PR. I have implemented it and reverted most of the changes by @Kypsis  and seems to be working now.

**Comment by ivaravi** [comment]
Sorry, missed out on @Kypsis commits. Now pulling again seemed break it as you said. Thanks!

**Comment by keeganmcbride** [comment]
It's okay, I made some small changes so master should build properly now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
